@startuml
title Diagrama de Secuencia - Solicitud de Préstamo y Monitoreo de Riesgo (DeFi360)

actor Usuario
boundary "Frontend Web" as Frontend
control "AuthController" as Auth
control "LoanController" as Loan
control "LTVService" as LTV
control "OracleService" as Oracle
control "RiskMonitor" as Risk
database "Base de Datos" as DB
collections "MockWallet" as Wallet
control "NotificationService" as Notify

== Inicio de Sesión ==

Usuario -> Frontend : Clic en "Conectar Wallet"
Frontend -> Auth : solicitarConexion()
Auth -> Wallet : conectarWallet()
Wallet --> Auth : datosWallet(balance, address)

Auth -> DB : registrarSesion()
DB --> Auth : sesión registrada

Auth --> Frontend : login exitoso + balance
Frontend --> Usuario : Mostrar Dashboard

== Solicitud de Préstamo ==

Usuario -> Frontend : Solicitar préstamo\n(Monto + Colateral)
Frontend -> Loan : crearSolicitud()

Loan -> Wallet : verificarFondosColateral()
Wallet --> Loan : colateral disponible

Loan -> LTV : calcularLTV(monto, colateral)

note right of LTV
LTV = (Monto Prestamo /
Valor Colateral) * 100
LTV= Loan to value, riesgo de un prestamo
end note

LTV --> Loan : LTV = 50%

alt LTV aceptable
    Loan -> Wallet : bloquearColateral()
    Wallet --> Loan : colateral bloqueado

    Loan -> DB : guardarPrestamo()
    DB --> Loan : préstamo registrado

    Loan --> Frontend : solicitud aprobada
    Frontend --> Usuario : Mostrar préstamo activo
else LTV muy alto
    Loan --> Frontend : rechazo de solicitud
    Frontend --> Usuario : Mostrar error de riesgo
end

== Pago de Cuota ==

Usuario -> Frontend : Pagar cuota
Frontend -> Loan : procesarPago()

Loan -> DB : actualizarSaldoPendiente()
DB --> Loan : saldo actualizado

Loan -> LTV : recalcularLTV()
LTV --> Loan : nuevo LTV = 65%

Loan -> DB : guardarNuevoLTV()
DB --> Loan : actualización correcta

Loan --> Frontend : pago exitoso
Frontend --> Usuario : Mostrar nuevo saldo y LTV

== Monitoreo de Riesgo ==

loop Cada cierto tiempo
    Risk -> Oracle : obtenerPrecioETH()
    Oracle --> Risk : nuevo precio ETH

    Risk -> DB : obtenerPrestamosActivos()
    DB --> Risk : lista préstamos

    Risk -> LTV : recalcularLTVGlobal()
    LTV --> Risk : LTV actualizado

    alt LTV >= 90%
        Risk -> Notify : enviarAlerta()
        Notify --> Usuario : Correo de alerta crítica
    end

    alt LTV >= 95%
        Risk -> Wallet : ejecutarLiquidacion()
        Wallet --> Risk : colateral liquidado

        Risk -> DB : actualizarEstadoPrestamo()
        DB --> Risk : estado liquidado

        Risk --> Usuario : préstamo liquidado
    end
end

@enduml